In [ ]:
!pip install datasets

Collecting dataset
  Downloading dataset-1.6.2-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting sqlalchemy<2.0.0,>=1.3.2 (from dataset)
  Downloading SQLAlchemy-1.4.54-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: alembic>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from dataset) (1.18.4)
Collecting banal>=1.0.1 (from dataset)
  Downloading banal-1.0.6-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=0.6.2->dataset) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=0.6.2->dataset) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<2.0.0,>=1.3.2->dataset) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=0.6.2->dataset) (3.0.3)
Downloading dataset-1.6.2-py2.py3-none-any.whl (18 kB)
Downloading banal-1.0.6-py2.py3-none-any.whl (6.1 kB)
Downloading SQLAlchemy-1.4.54-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 42.6 MB/s eta 0:00:00
Installing collected packages: banal, sqlalchemy, dataset
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.48
    Uninstalling SQLAlchemy-2.0.48:
      Successfully uninstalled SQLAlchemy-2.0.48
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.54 which is incompatible.
google-adk 1.27.1 requires sqlalchemy<3.0.0,>=2.0, but you have sqlalchemy 1.4.54 which is incompatible.
Successfully installed banal-1.0.6 dataset-1.6.2 sqlalchemy-1.4.54

In [ ]:
from datasets import load_dataset

ds = load_dataset("roneneldan/TinyStories")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00000-of-00004-2d5a1467fff108(…):   0%|          | 0.00/249M [00:00<?, ?B/s]

data/train-00001-of-00004-5852b56a2bd28f(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

data/train-00002-of-00004-a26307300439e9(…):   0%|          | 0.00/246M [00:00<?, ?B/s]

data/train-00003-of-00004-d243063613e5a0(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

data/validation-00000-of-00001-869c898b5(…):   0%|          | 0.00/9.99M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2119719 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/21990 [00:00<?, ? examples/s]

In [ ]:
!pip install transformers datasets accelerate -q

In [ ]:
from datasets import load_dataset

ds = load_dataset("roneneldan/TinyStories")
print(ds)
print("\nSample story:")
print(ds['train'][0]['text'])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00004-2d5a1467fff108(…):   0%|          | 0.00/249M [00:00<?, ?B/s]

data/train-00001-of-00004-5852b56a2bd28f(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00002-of-00004-a26307300439e9(…):   0%|          | 0.00/246M [00:00<?, ?B/s]

data/train-00003-of-00004-d243063613e5a0(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

data/validation-00000-of-00001-869c898b5(…):   0%|          | 0.00/9.99M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2119719 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/21990 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 2119719
    })
    validation: Dataset({
        features: ['text'],
        num_rows: 21990
    })
})

Sample story:
One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.

Lily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."

Together, they shared the needle and sewed the button on Lily's shirt. It was not difficult for them because they were sharing and helping each other. After they finished, Lily thanked her mom for sharing the needle and fixing her shirt. They both felt happy because they had shared and worked together.

In [ ]:
import os
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "120"  # increase timeout to 2 min

from transformers import GPT2Tokenizer, GPT2LMHeadModel

# Load base model with increased timeout
base_tokenizer = GPT2Tokenizer.from_pretrained("gpt2", timeout=120)
base_tokenizer.pad_token = base_tokenizer.eos_token
base_model = GPT2LMHeadModel.from_pretrained("gpt2")

print("Base model loaded!")
print(f"Parameters: {base_model.num_parameters():,}")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Error while downloading from https://huggingface.co/gpt2/resolve/main/tokenizer.json: The read operation timed out
Trying to resume download...
WARNING:huggingface_hub.file_download:Error while downloading from https://huggingface.co/gpt2/resolve/main/tokenizer.json: The read operation timed out
Trying to resume download...

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Base model loaded!
Parameters: 124,439,808

In [ ]:
# Use 50k stories for training — enough to see clear improvement, trains in ~1.5hrs on Colab T4
train_subset = ds['train'].select(range(50000))
val_subset   = ds['validation'].select(range(2000))

def tokenize(batch):
    tokens = tokenizer(
        batch['text'],
        truncation=True,
        max_length=256,
        padding='max_length',
    )
    tokens['labels'] = tokens['input_ids'].copy()
    return tokens

train_tokenized = train_subset.map(tokenize, batched=True, remove_columns=['text'])
val_tokenized   = val_subset.map(tokenize,   batched=True, remove_columns=['text'])

train_tokenized.set_format('torch')
val_tokenized.set_format('torch')

print(f"Train samples: {len(train_tokenized)}")
print(f"Val samples:   {len(val_tokenized)}")

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Train samples: 50000
Val samples:   2000

In [ ]:
from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./tinystories-gpt2",
    num_train_epochs=2,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=200,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=500,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True,                    # uses less VRAM, faster on T4
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=data_collator,
)

trainer.train()
print("Training complete!")

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Training complete!

In [ ]:
model.save_pretrained("./tinystories-gpt2-final")
tokenizer.save_pretrained("./tinystories-gpt2-final")

# Also save to Google Drive so you don't lose it when Colab disconnects
from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.copytree("./tinystories-gpt2-final", "/content/drive/MyDrive/tinystories-gpt2-final")
print("Saved to Google Drive!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Mounted at /content/drive
Saved to Google Drive!

In [ ]:
from transformers import pipeline

generator = pipeline('text-generation', model="./tinystories-gpt2-final", tokenizer=tokenizer)

prompts = [
    "Once upon a time, a little girl named Sara found a magical",
    "Ali was a brave boy who loved adventures. One day he",
    "In a forest far away, there lived a friendly dragon who",
]

for prompt in prompts:
    result = generator(prompt, max_length=150, num_return_sequences=1, temperature=0.8, do_sample=True)
    print("PROMPT:", prompt)
    print("OUTPUT:", result[0]['generated_text'])
    print("-" * 60)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Passing `generation_config` together with generation-related arguments=({'max_length', 'num_return_sequences', 'do_sample', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=256) and `max_length`(=150) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=150) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

PROMPT: Once upon a time, a little girl named Sara found a magical
OUTPUT: Once upon a time, a little girl named Sara found a magical door. The door was big and had a knob. Sara didn't know what was inside the door, but she couldn't help but smile.

Sara showed her friend, a little boy named Tim, the door. Tim asked, "What's inside the door?"

Sara replied, "A magic door!" Tim was excited and asked, "What's a magic door?"

Sara explained, "A magic door is when a big idea comes into being. That means you can create something special with this door."

Tim was even more excited and asked, "Can you do that?"

Sara said, "Yes, I can do it!" And they both started to create something magical inside the magical door. They felt so happy and excited.

The magic door opened, and they all went on a magical adventure. They had so much fun that they decided to keep the door magical forever. The end. The end. The end. The end. Sara said, "I'm so glad I found this magical door." and the magic door closed. The little girl and Tim went home, happy and safe. They learned that sometimes, magic is just the thing that happens. And they all lived happily ever after.
------------------------------------------------------------

Both `max_new_tokens` (=256) and `max_length`(=150) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

PROMPT: Ali was a brave boy who loved adventures. One day he
OUTPUT: Ali was a brave boy who loved adventures. One day he decided to go on an adventure. He had a great idea! He asked his mom why he was going on a big adventure.

His mom said "It's important to be ready and ready for adventure."

John looked around. He saw a big lake and he wanted to go there. He ran towards it and started to push himself.

He pushed himself and pushed the water around. He pushed himself into the lake. Everywhere he went, he pushed.

Suddenly, he heard a loud cry coming from the lake. He looked around and saw two children standing there. They were crying.

John's mom said "Don't worry, John. We will help you. We will show you how to get to the top of the lake."

John smiled and said "Yes, we will show you how." He grabbed a bucket and filled it with water. He pushed himself back and forth until he reached the bottom of the lake. He made it back to his house.

Mom said "See what we can do, you can push like crazy!" The two children nodded and laughed. They stayed friends until it was time to go home.

They had a great day and John was proud. He had been ready for
------------------------------------------------------------
PROMPT: In a forest far away, there lived a friendly dragon who
OUTPUT: In a forest far away, there lived a friendly dragon who loved to play. He liked to roar and giggle with all his might.

One day, the dragon met a big, mean wolf. The wolf was not friendly to dragons, but it knew something was wrong. The dragon wanted to help the wolf, but he had no friend.

The dragon had an idea. He said to the wolf, "We can have a small, harmless friend. That's what you have. That means no more monsters and no more animals."

The wolf thought this was a great idea and they all tried to play together. They jumped and swung and chased the wolf. They played games of tag and hug-buddy.

At last, the wolf found a friend. The friendly dragon welcomed the wolf and they became best friends. They both lived happily ever after.

The end. The dragon and the wolf were both happy and wise. They lived happily ever after. And the friendly dragon never saw any monsters again. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end. The end.
------------------------------------------------------------

In [ ]:
import math

# Perplexity — lower is better, measures how well model predicts children's stories
eval_results = trainer.evaluate()
perplexity = math.exp(eval_results['eval_loss'])

print(f"Eval Loss:   {eval_results['eval_loss']:.4f}")
print(f"Perplexity:  {perplexity:.2f}")
print()
print("--- For your report ---")
print(f"Fine-tuned GPT-2 perplexity on TinyStories validation set: {perplexity:.2f}")
print("(Lower perplexity = model understands children's story style better)")

Eval Loss:   1.5711
Perplexity:  4.81

--- For your report ---
Fine-tuned GPT-2 perplexity on TinyStories validation set: 4.81
(Lower perplexity = model understands children's story style better)

In [ ]:
# Cell 1 - Install
!pip install transformers datasets accelerate -q

In [ ]:
# ============================================================
#  KIDS STORY GPT-2 FINE-TUNING — COMPLETE IN ONE CELL
# ============================================================

# 1. Install
import subprocess
subprocess.run(["pip", "install", "transformers", "datasets", "accelerate", "-q"])

# 2. Mount Drive first so everything saves there
from google.colab import drive
drive.mount('/content/drive')

SAVE_PATH = "/content/drive/MyDrive/tinystories-gpt2-final"

# 3. Imports
from datasets import load_dataset
from transformers import (
    GPT2Tokenizer, GPT2LMHeadModel,
    TrainingArguments, Trainer,
    DataCollatorForLanguageModeling
)
import os, math

# 4. Load dataset
print("Loading dataset...")
ds = load_dataset("roneneldan/TinyStories")
print(f"Train: {len(ds['train'])} | Val: {len(ds['validation'])}")

# 5. Load model
print("Loading GPT-2...")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained("gpt2")
print(f"Parameters: {model.num_parameters():,}")

# 6. Tokenize (50k train, 2k val)
print("Tokenizing...")
def tokenize(batch):
    tokens = tokenizer(batch['text'], truncation=True, max_length=256, padding='max_length')
    tokens['labels'] = tokens['input_ids'].copy()
    return tokens

train_tok = ds['train'].select(range(50000)).map(tokenize, batched=True, remove_columns=['text'])
val_tok   = ds['validation'].select(range(2000)).map(tokenize, batched=True, remove_columns=['text'])
train_tok.set_format('torch')
val_tok.set_format('torch')
print("Tokenized!")

# 7. Train — saves checkpoints directly to Drive
print("Training... (this takes ~1.5 hours, you can close the tab)")
args = TrainingArguments(
    output_dir=SAVE_PATH,
    num_train_epochs=2,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=200,
    weight_decay=0.01,
    logging_steps=500,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=1,
    load_best_model_at_end=True,
    fp16=True,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False),
)

trainer.train()

# 8. Save final model + tokenizer to Drive
print("Saving to Drive...")
trainer.save_model(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

# 9. Verify
print("\nFiles saved:")
for f in os.listdir(SAVE_PATH):
    size = os.path.getsize(f"{SAVE_PATH}/{f}")
    print(f"  {f}  ({size/1024/1024:.1f} MB)")

# 10. Evaluate
eval_results = trainer.evaluate()
perplexity = math.exp(eval_results['eval_loss'])
print(f"\nEval Loss:  {eval_results['eval_loss']:.4f}")
print(f"Perplexity: {perplexity:.2f}")

# 11. Quick generation test
from transformers import pipeline
gen = pipeline('text-generation', model=SAVE_PATH, tokenizer=tokenizer)
result = gen(
    "Once upon a time, a little boy named Ali found a mysterious map",
    max_length=150, do_sample=True, temperature=0.8
)
print("\nSample output:")
print(result[0]['generated_text'])

print("\nDONE! Model saved to Google Drive.")

Mounted at /content/drive
Loading dataset...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00004-2d5a1467fff108(…):   0%|          | 0.00/249M [00:00<?, ?B/s]

data/train-00001-of-00004-5852b56a2bd28f(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00002-of-00004-a26307300439e9(…):   0%|          | 0.00/246M [00:00<?, ?B/s]

data/train-00003-of-00004-d243063613e5a0(…):   0%|          | 0.00/248M [00:00<?, ?B/s]

data/validation-00000-of-00001-869c898b5(…):   0%|          | 0.00/9.99M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2119719 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/21990 [00:00<?, ? examples/s]

Train: 2119719 | Val: 21990
Loading GPT-2...

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Parameters: 124,439,808
Tokenizing...

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Tokenized!
Training... (this takes ~1.5 hours, you can close the tab)

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Saving to Drive...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Files saved:
  generation_config.json  (0.0 MB)
  config.json  (0.0 MB)
  tokenizer_config.json  (0.0 MB)
  tokenizer.json  (3.4 MB)
  checkpoint-6250  (0.0 MB)
  model.safetensors  (474.7 MB)
  training_args.bin  (0.0 MB)

Eval Loss:  1.5711
Perplexity: 4.81

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Passing `generation_config` together with generation-related arguments=({'temperature', 'max_length', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=256) and `max_length`(=150) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Sample output:
Once upon a time, a little boy named Ali found a mysterious map in his backyard. He was very excited. He wanted to find out what was inside the map.

So Ali went to his neighbor's house. He showed her the map and asked, "What is this map, Ali?"

His neighbor replied, "It's a map, but it's also a treasure map. It tells us everything about where you come from and what you can do."

Ali was very curious. He peeked through the map and found a hidden door. He opened it and inside was a treasure map. He was so happy.

Ali went back home and asked his mom what the treasure map said. Her mom said, "I don't know, but it's very mysterious and fun."

So Ali went to play with his friends and found the treasure map. He wanted to see all the hidden things inside. So he went inside and got a new map to keep his friends safe.

And the end. Ali was very happy. He learned that even if it's a mystery, it's still a bit hard to know everything. And the map was fun to look through. And he learned that even when things seem mysterious, knowing the answers really makes a difference. The end.

The end

DONE! Model saved to Google Drive.

In [ ]:
import os

print("Files in Drive folder:")
for f in os.listdir("/content/drive/MyDrive/tinystories-gpt2-final"):
    size = os.path.getsize(f"/content/drive/MyDrive/tinystories-gpt2-final/{f}")
    print(f"  {f}  ({size/1024/1024:.1f} MB)")

Files in Drive folder:
  generation_config.json  (0.0 MB)
  config.json  (0.0 MB)
  tokenizer_config.json  (0.0 MB)
  tokenizer.json  (3.4 MB)
  checkpoint-6250  (0.0 MB)
  model.safetensors  (474.7 MB)
  training_args.bin  (0.0 MB)

In [ ]:
# ── Load your fine-tuned model ──────────────────────────────────────────────
from transformers import GPT2Tokenizer, GPT2LMHeadModel, pipeline
import torch, math

SAVE_PATH = "/content/drive/MyDrive/tinystories-gpt2-final"

tokenizer = GPT2Tokenizer.from_pretrained(SAVE_PATH)
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained(SAVE_PATH)
model.eval()
print("Fine-tuned model loaded!")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

Fine-tuned model loaded!

In [ ]:
# ── Load BASE GPT-2 for comparison ───────────────────────────────────────────
import os
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "120"

base_tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
base_tokenizer.pad_token = base_tokenizer.eos_token
base_model = GPT2LMHeadModel.from_pretrained("gpt2")
base_model.eval()
print("Base model loaded!")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Base model loaded!

In [ ]:
# ── Perplexity comparison ────────────────────────────────────────────────────
from datasets import load_dataset

ds = load_dataset("roneneldan/TinyStories")
samples = ds['validation'].select(range(200))

def compute_perplexity(mdl, tok, samples):
    total_loss, count = 0, 0
    with torch.no_grad():
        for item in samples:
            enc = tok(item['text'], return_tensors='pt',
                      truncation=True, max_length=256)
            out = mdl(**enc, labels=enc['input_ids'])
            total_loss += out.loss.item()
            count += 1
    return math.exp(total_loss / count)

print("Computing perplexity (takes ~2 min)...")
base_ppl   = compute_perplexity(base_model,   base_tokenizer, samples)
tuned_ppl  = compute_perplexity(model,        tokenizer,      samples)

print(f"\n{'='*45}")
print(f"  Base GPT-2 perplexity:        {base_ppl:.2f}")
print(f"  Fine-tuned GPT-2 perplexity:  {tuned_ppl:.2f}")
print(f"  Improvement:                  {base_ppl/tuned_ppl:.1f}x better")
print(f"{'='*45}")
print("\n--- COPY THIS FOR YOUR REPORT ---")
print(f"Base GPT-2:        {base_ppl:.2f}")
print(f"Fine-tuned GPT-2:  {tuned_ppl:.2f}")
print(f"Improvement:       {base_ppl/tuned_ppl:.1f}x")

Computing perplexity (takes ~2 min)...

=============================================
  Base GPT-2 perplexity:        10.44
  Fine-tuned GPT-2 perplexity:  3.68
  Improvement:                  2.8x better
=============================================

--- COPY THIS FOR YOUR REPORT ---
Base GPT-2:        10.44
Fine-tuned GPT-2:  3.68
Improvement:       2.8x

In [ ]:
# ── Side by side quality comparison ─────────────────────────────────────────
base_gen  = pipeline('text-generation', model=base_model,  tokenizer=base_tokenizer)
tuned_gen = pipeline('text-generation', model=model,       tokenizer=tokenizer)

prompts = [
    "Once upon a time, a little boy named Ali found a mysterious map",
    "Sara wanted to keep the baby bird forever, but",
    "The dragon offered Omar great power, but",
]

for prompt in prompts:
    print("=" * 55)
    print(f"PROMPT: {prompt}")
    print("-" * 55)
    r1 = base_gen(prompt,  max_length=120, do_sample=True, temperature=0.8)
    r2 = tuned_gen(prompt, max_length=120, do_sample=True, temperature=0.8)
    print(f"BASE GPT-2:\n{r1[0]['generated_text']}\n")
    print(f"FINE-TUNED:\n{r2[0]['generated_text']}\n")

Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=======================================================
PROMPT: Once upon a time, a little boy named Ali found a mysterious map
-------------------------------------------------------

Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

BASE GPT-2:
Once upon a time, a little boy named Ali found a mysterious map by accident. The map had always been a mystery to him, but his parents were interested in finding it. He was so excited about finding it that he gave it to his father, but just then his father found out about it, and he asked his uncle why he did it. He was shocked, thinking his father was a genius, and he said, "He's a genius." He would love to make a map that would give him the answers to the mysteries. So he came across this map, and he came across a little boy named Ali.

Ali, who was about the age of four, and his father's older brother, called him "Ali" as he walked about in the house. Ali took a step forward and said, "Ali, what do you mean? I can see a little place you can come from." Ali's father, then, decided that Ali might be able to give him some clues. They contacted the library, and they found a room that had been set aside for Ali.

Ali grew up in a very strange place. The library was a very quiet place, with only one desk and a few books. When it opened up, people were sitting around, reading and talking. Eventually, Ali found out that a

FINE-TUNED:
Once upon a time, a little boy named Ali found a mysterious map. The map had a big red line and it showed him where to go. Ali was very happy to find the map and ran to show his friends.

But when he got there, it was too late. Ali's friends were too busy playing with the map to notice the map. They all started singing and laughing. Ali felt sad because he had lost his map.

But then, Ali's mom saw him and said, "It's okay. We can find it together." So they did. They searched and searched until they found the mysterious map. Ali was so happy and he thanked his mom to show her his map. From that day on, Ali and his friends always looked for new surprises in the mysterious map. The end. Ali was so happy that he found his map because he was able to show his friends his amazing discovery. The end. The End. Ali was very happy that he found his map and he was very proud of himself for finding it. The end. Ali was so proud of himself and he felt very happy that he found his map. The end. Ali was very proud of himself for finding his special map. The end. The end. Ali was tired after all that. He was tired too. He promised himself he

=======================================================
PROMPT: Sara wanted to keep the baby bird forever, but
-------------------------------------------------------

Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

BASE GPT-2:
Sara wanted to keep the baby bird forever, but he said he would never go on record as saying he wanted to kill the girl.

The girl, who was 13, said she was born in the 1980s to a devout Catholic mother and a devout Muslim mother.

"You're always looking for ways to get to know each other," she said. "I can't imagine how things would work if I were to end up in jail. I feel like I'm making a mistake. I was raised by an Irish family; we had a great history.

"I've never seen myself as a murderer. I'm always looking for ways to get to know each other, and that's something I don't really agree with."

READ MORE:

FINE-TUNED:
Sara wanted to keep the baby bird forever, but it was too much for her. She wanted to pet it, but it was too cold. She wanted to be her friend, but she was scared. She could not fly like the bird, but she could smell the cold.

One day, her mom took her to the park to play. She saw the baby bird and said, "Sara, come here. The baby bird is cold. It needs a warm place."

Sara said, "Okay, mom, I will come. But first, I will bathe." She got off the bench and put on her mom's wet clothes. Then she walked to the baby bird and gave it a bath.

The baby bird was happy and started to swim. Sara and her mom watched and laughed. Sara said, "You did a good job. The baby bird is soft now. You are so graceful. I wish I could fly like you."

Sara was happy again. She said, "Thank you, mom. You were very kind. I wish I could be my friend too."

Sara said, "I will always be your friend. It will make you happy and make you happy." She felt happy and happy. She said, "Okay, mom

=======================================================
PROMPT: The dragon offered Omar great power, but
-------------------------------------------------------

Both `max_new_tokens` (=256) and `max_length`(=120) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

BASE GPT-2:
The dragon offered Omar great power, but the dragons did not want anyone to be afraid of him, so Omar was hesitant to fight him. A few years later, he and his brother Aisha married. They were married in the desert, and when he returned, he was still in the mountains, waiting to pass through the city again.

After being captured by the guards, Omar took his place in a large wooden structure, and was released from the Dragon Tower. However, his sister, who was living on the lower level, was captured by the guards and taken to the dungeon, where she was tortured to death. One day, a young girl named Abbi, who was a dragon's apprentice, was killed by the guards.

Abbi's body was covered in blood and a large hole in the ground was opened with a stone to the right, and it is said that she was the only person that had survived the dragon attack. It is also said that she was poisoned by a dragon's venom.

As a dragon, Abbi is an extremely formidable fighter, but she is also prone to being the most powerful and feared creature on the planet, and especially after being trapped under a dragon for two years.

Abbi was the first lady who passed away in the future.

FINE-TUNED:
The dragon offered Omar great power, but he was too scared of it. He didn't like to accept it. He wanted to be brave and be strong. He kept asking for and it didn't budge.

One day, Omar heard a loud scream. It was his friend, a girl named Lily. She was angry at the dragon. She thought he was mean, and she wanted to be his friend too.

Moral of the story: If you accept things that aren't yours, you won't get what you want. You might get a bad ending.

Omar listened to his friend and decided to accept it. After a long time of searching, Omar finally accepted the dragon. He was very happy and thanked his friend. From that day on, Omar never told anyone about the dragon. He knew that he had accepted the dragon and made it to be brave. He learned that accepting anything isn't as important as being brave and strong.

The moral of the story: Accepting and accepting can make you happy and even more powerful. Enjoying something that isn't yours isn't bad, it's more powerful and wonderful. And it's always better to accept and become the best you can be. Who knows, maybe someday Omar will be brave enough to accept something